# Generated by Django 5.1.6 on 2025-06-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20201201_0712'),
        ('files', '0004_alter_subtitle_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='for not logged in users', max_length=33, null=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('report', 'Report'), ('rate', 'Rate')], default='watch', max_length=20)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentactions', to='files.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action', '-action_date'], name='actions_com_user_id_e418e7_idx'), models.Index(fields=['session_key', 'action'], name='actions_com_session_19cc95_idx')],
            },
        ),
    ]
