# Generated by Django 5.1.6 on 2025-06-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language__title']},
        ),
    ]
