# Generated by Django 5.1.6 on 2026-05-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_subtitle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cast',
            field=models.TextField(blank=True, help_text='主演 / 主创（以影片中名单整理）'),
        ),
        migrations.AddField(
            model_name='media',
            name='chief_instructor',
            field=models.CharField(blank=True, help_text='总指导', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='director',
            field=models.CharField(blank=True, help_text='导演', max_length=200),
        ),
        migrations.AddField(
            model_name='media',
            name='editor',
            field=models.CharField(blank=True, help_text='剪辑制作者', max_length=200),
        ),
        migrations.AddField(
            model_name='media',
            name='film_code',
            field=models.CharField(blank=True, db_index=True, help_text='片号，如 Z20 / G49 / F1', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='filming_location',
            field=models.CharField(blank=True, help_text='取景地', max_length=200),
        ),
        migrations.AddField(
            model_name='media',
            name='premiere_date',
            field=models.DateField(blank=True, help_text='首发时间（影片最早首发的日期，可能早于上传影院时间）', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='premiere_location',
            field=models.CharField(blank=True, help_text='首发地（如 知乎 / 影院 / 某视频号）', max_length=200),
        ),
    ]
